### ISSUE TITLE
Two errors raise up when running the code:  ('Data' object has .... ) & ('VGAE' object has no ...)

### ISSUE THREAD

**Issue by abdalgader-a-zz** [joeybose/Meta-Graph#3]
Hello @joeybose, 

The following two errors have been raised when I run the code passing the arguments in the first line in 'run_ppi_best_gs.sh'. 

- File: '.../maml.py", line 84, in meta_gradient_step  x, train_pos_edge_index = data_graph.x.to(args.dev), data_graph.train_pos_edge_index.to(args.dev)
**_AttributeError: 'Data' object has no attribute 'train_pos_edge_index'_** 

- File ".../anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 576, in  ,__getattr__type(self).__name__n, name))
**_AttributeError: 'VGAE' object has no attribute 'split_edges'_**

Although  VGAE inherits from GAE which has the 'spit_edges(...)' function.

knowing that I've installed  the following packages:
> torch-cluster             1.5.4                    
> torch-geometric           1.5.0                    
> torch-scatter             2.0.4                    
> torch-sparse              0.6.3                   
> torch-spline-conv         1.2.0      

what do you think the problems came from?

**Comment by joeybose** [comment]
Can you tell me which command is throwing that error? I can't reproduce this error using the basic commands. So the first error is due to the fact that edges have not been partitioned into train/test/val which is precisely what the VGAE split_edges function is supposed to do. So these two errors are linked.

**Comment by abdalgader-a-zz** [comment]
Here the command

https://github.com/joeybose/Meta-Graph/blob/c5ef8d48433737d1f1d648b816a1abccf96eb724/run_ppi_best_gs.sh#L6

I don't know why the split_edges function hasn't been recognized as a member of VGAE that has been inherited from GAE? which is caused the first error as I understand from what you said.

**Comment by joeybose** [comment]
That command now works for me now. So the problem was due to the fact that the new version of pytorch_geometric had removed the split_edges function from the autoencoder file. I've updated the codebase to fix this so now it should run fine. However, I haven't checked all other possible experiments so if you do find another error due to porting issues do let me know.

**Comment by abdalgader-a-zz** [comment]
Great! It works now. Thanks!
